version: "3"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "user"
      MYSQL_DATABASE: "testing"
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
      - "./dump:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 88:80
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "user"
